#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iterator>
#include <algorithm>
#include "AI.cpp"
#include "base/BaseModel.cpp"
#include "_Reader.cpp"
#include "_Book.cpp"
#include "_Inventory.cpp"
